pub const KNOWN_CITIES: [&[u8]; 413] = [
    "Abha".as_bytes(),
    "Abidjan".as_bytes(),
    "Abéché".as_bytes(),
    "Accra".as_bytes(),
    "Addis Ababa".as_bytes(),
    "Adelaide".as_bytes(),
    "Aden".as_bytes(),
    "Ahvaz".as_bytes(),
    "Albuquerque".as_bytes(),
    "Alexandra".as_bytes(),
    "Alexandria".as_bytes(),
    "Algiers".as_bytes(),
    "Alice Springs".as_bytes(),
    "Almaty".as_bytes(),
    "Amsterdam".as_bytes(),
    "Anadyr".as_bytes(),
    "Anchorage".as_bytes(),
    "Andorra la Vella".as_bytes(),
    "Ankara".as_bytes(),
    "Antananarivo".as_bytes(),
    "Antsiranana".as_bytes(),
    "Arkhangelsk".as_bytes(),
    "Ashgabat".as_bytes(),
    "Asmara".as_bytes(),
    "Assab".as_bytes(),
    "Astana".as_bytes(),
    "Athens".as_bytes(),
    "Atlanta".as_bytes(),
    "Auckland".as_bytes(),
    "Austin".as_bytes(),
    "Baghdad".as_bytes(),
    "Baguio".as_bytes(),
    "Baku".as_bytes(),
    "Baltimore".as_bytes(),
    "Bamako".as_bytes(),
    "Bangkok".as_bytes(),
    "Bangui".as_bytes(),
    "Banjul".as_bytes(),
    "Barcelona".as_bytes(),
    "Bata".as_bytes(),
    "Batumi".as_bytes(),
    "Beijing".as_bytes(),
    "Beirut".as_bytes(),
    "Belgrade".as_bytes(),
    "Belize City".as_bytes(),
    "Benghazi".as_bytes(),
    "Bergen".as_bytes(),
    "Berlin".as_bytes(),
    "Bilbao".as_bytes(),
    "Birao".as_bytes(),
    "Bishkek".as_bytes(),
    "Bissau".as_bytes(),
    "Blantyre".as_bytes(),
    "Bloemfontein".as_bytes(),
    "Boise".as_bytes(),
    "Bordeaux".as_bytes(),
    "Bosaso".as_bytes(),
    "Boston".as_bytes(),
    "Bouaké".as_bytes(),
    "Bratislava".as_bytes(),
    "Brazzaville".as_bytes(),
    "Bridgetown".as_bytes(),
    "Brisbane".as_bytes(),
    "Brussels".as_bytes(),
    "Bucharest".as_bytes(),
    "Budapest".as_bytes(),
    "Bujumbura".as_bytes(),
    "Bulawayo".as_bytes(),
    "Burnie".as_bytes(),
    "Busan".as_bytes(),
    "Cabo San Lucas".as_bytes(),
    "Cairns".as_bytes(),
    "Cairo".as_bytes(),
    "Calgary".as_bytes(),
    "Canberra".as_bytes(),
    "Cape Town".as_bytes(),
    "Changsha".as_bytes(),
    "Charlotte".as_bytes(),
    "Chiang Mai".as_bytes(),
    "Chicago".as_bytes(),
    "Chihuahua".as_bytes(),
    "Chittagong".as_bytes(),
    "Chișinău".as_bytes(),
    "Chongqing".as_bytes(),
    "Christchurch".as_bytes(),
    "City of San Marino".as_bytes(),
    "Colombo".as_bytes(),
    "Columbus".as_bytes(),
    "Conakry".as_bytes(),
    "Copenhagen".as_bytes(),
    "Cotonou".as_bytes(),
    "Cracow".as_bytes(),
    "Da Lat".as_bytes(),
    "Da Nang".as_bytes(),
    "Dakar".as_bytes(),
    "Dallas".as_bytes(),
    "Damascus".as_bytes(),
    "Dampier".as_bytes(),
    "Dar es Salaam".as_bytes(),
    "Darwin".as_bytes(),
    "Denpasar".as_bytes(),
    "Denver".as_bytes(),
    "Detroit".as_bytes(),
    "Dhaka".as_bytes(),
    "Dikson".as_bytes(),
    "Dili".as_bytes(),
    "Djibouti".as_bytes(),
    "Dodoma".as_bytes(),
    "Dolisie".as_bytes(),
    "Douala".as_bytes(),
    "Dubai".as_bytes(),
    "Dublin".as_bytes(),
    "Dunedin".as_bytes(),
    "Durban".as_bytes(),
    "Dushanbe".as_bytes(),
    "Edinburgh".as_bytes(),
    "Edmonton".as_bytes(),
    "El Paso".as_bytes(),
    "Entebbe".as_bytes(),
    "Erbil".as_bytes(),
    "Erzurum".as_bytes(),
    "Fairbanks".as_bytes(),
    "Fianarantsoa".as_bytes(),
    "Flores,  Petén".as_bytes(),
    "Frankfurt".as_bytes(),
    "Fresno".as_bytes(),
    "Fukuoka".as_bytes(),
    "Gaborone".as_bytes(),
    "Gabès".as_bytes(),
    "Gagnoa".as_bytes(),
    "Gangtok".as_bytes(),
    "Garissa".as_bytes(),
    "Garoua".as_bytes(),
    "George Town".as_bytes(),
    "Ghanzi".as_bytes(),
    "Gjoa Haven".as_bytes(),
    "Guadalajara".as_bytes(),
    "Guangzhou".as_bytes(),
    "Guatemala City".as_bytes(),
    "Halifax".as_bytes(),
    "Hamburg".as_bytes(),
    "Hamilton".as_bytes(),
    "Hanga Roa".as_bytes(),
    "Hanoi".as_bytes(),
    "Harare".as_bytes(),
    "Harbin".as_bytes(),
    "Hargeisa".as_bytes(),
    "Hat Yai".as_bytes(),
    "Havana".as_bytes(),
    "Helsinki".as_bytes(),
    "Heraklion".as_bytes(),
    "Hiroshima".as_bytes(),
    "Ho Chi Minh City".as_bytes(),
    "Hobart".as_bytes(),
    "Hong Kong".as_bytes(),
    "Honiara".as_bytes(),
    "Honolulu".as_bytes(),
    "Houston".as_bytes(),
    "Ifrane".as_bytes(),
    "Indianapolis".as_bytes(),
    "Iqaluit".as_bytes(),
    "Irkutsk".as_bytes(),
    "Istanbul".as_bytes(),
    "Jacksonville".as_bytes(),
    "Jakarta".as_bytes(),
    "Jayapura".as_bytes(),
    "Jerusalem".as_bytes(),
    "Johannesburg".as_bytes(),
    "Jos".as_bytes(),
    "Juba".as_bytes(),
    "Kabul".as_bytes(),
    "Kampala".as_bytes(),
    "Kandi".as_bytes(),
    "Kankan".as_bytes(),
    "Kano".as_bytes(),
    "Kansas City".as_bytes(),
    "Karachi".as_bytes(),
    "Karonga".as_bytes(),
    "Kathmandu".as_bytes(),
    "Khartoum".as_bytes(),
    "Kingston".as_bytes(),
    "Kinshasa".as_bytes(),
    "Kolkata".as_bytes(),
    "Kuala Lumpur".as_bytes(),
    "Kumasi".as_bytes(),
    "Kunming".as_bytes(),
    "Kuopio".as_bytes(),
    "Kuwait City".as_bytes(),
    "Kyiv".as_bytes(),
    "Kyoto".as_bytes(),
    "La Ceiba".as_bytes(),
    "La Paz".as_bytes(),
    "Lagos".as_bytes(),
    "Lahore".as_bytes(),
    "Lake Havasu City".as_bytes(),
    "Lake Tekapo".as_bytes(),
    "Las Palmas de Gran Canaria".as_bytes(),
    "Las Vegas".as_bytes(),
    "Launceston".as_bytes(),
    "Lhasa".as_bytes(),
    "Libreville".as_bytes(),
    "Lisbon".as_bytes(),
    "Livingstone".as_bytes(),
    "Ljubljana".as_bytes(),
    "Lodwar".as_bytes(),
    "Lomé".as_bytes(),
    "London".as_bytes(),
    "Los Angeles".as_bytes(),
    "Louisville".as_bytes(),
    "Luanda".as_bytes(),
    "Lubumbashi".as_bytes(),
    "Lusaka".as_bytes(),
    "Luxembourg City".as_bytes(),
    "Lviv".as_bytes(),
    "Lyon".as_bytes(),
    "Madrid".as_bytes(),
    "Mahajanga".as_bytes(),
    "Makassar".as_bytes(),
    "Makurdi".as_bytes(),
    "Malabo".as_bytes(),
    "Malé".as_bytes(),
    "Managua".as_bytes(),
    "Manama".as_bytes(),
    "Mandalay".as_bytes(),
    "Mango".as_bytes(),
    "Manila".as_bytes(),
    "Maputo".as_bytes(),
    "Marrakesh".as_bytes(),
    "Marseille".as_bytes(),
    "Maun".as_bytes(),
    "Medan".as_bytes(),
    "Mek'ele".as_bytes(),
    "Melbourne".as_bytes(),
    "Memphis".as_bytes(),
    "Mexicali".as_bytes(),
    "Mexico City".as_bytes(),
    "Miami".as_bytes(),
    "Milan".as_bytes(),
    "Milwaukee".as_bytes(),
    "Minneapolis".as_bytes(),
    "Minsk".as_bytes(),
    "Mogadishu".as_bytes(),
    "Mombasa".as_bytes(),
    "Monaco".as_bytes(),
    "Moncton".as_bytes(),
    "Monterrey".as_bytes(),
    "Montreal".as_bytes(),
    "Moscow".as_bytes(),
    "Mumbai".as_bytes(),
    "Murmansk".as_bytes(),
    "Muscat".as_bytes(),
    "Mzuzu".as_bytes(),
    "N'Djamena".as_bytes(),
    "Naha".as_bytes(),
    "Nairobi".as_bytes(),
    "Nakhon Ratchasima".as_bytes(),
    "Napier".as_bytes(),
    "Napoli".as_bytes(),
    "Nashville".as_bytes(),
    "Nassau".as_bytes(),
    "Ndola".as_bytes(),
    "New Delhi".as_bytes(),
    "New Orleans".as_bytes(),
    "New York City".as_bytes(),
    "Ngaoundéré".as_bytes(),
    "Niamey".as_bytes(),
    "Nicosia".as_bytes(),
    "Niigata".as_bytes(),
    "Nouadhibou".as_bytes(),
    "Nouakchott".as_bytes(),
    "Novosibirsk".as_bytes(),
    "Nuuk".as_bytes(),
    "Odesa".as_bytes(),
    "Odienné".as_bytes(),
    "Oklahoma City".as_bytes(),
    "Omaha".as_bytes(),
    "Oranjestad".as_bytes(),
    "Oslo".as_bytes(),
    "Ottawa".as_bytes(),
    "Ouagadougou".as_bytes(),
    "Ouahigouya".as_bytes(),
    "Ouarzazate".as_bytes(),
    "Oulu".as_bytes(),
    "Palembang".as_bytes(),
    "Palermo".as_bytes(),
    "Palm Springs".as_bytes(),
    "Palmerston North".as_bytes(),
    "Panama City".as_bytes(),
    "Parakou".as_bytes(),
    "Paris".as_bytes(),
    "Perth".as_bytes(),
    "Petropavlovsk-Kamchatsky".as_bytes(),
    "Philadelphia".as_bytes(),
    "Phnom Penh".as_bytes(),
    "Phoenix".as_bytes(),
    "Pittsburgh".as_bytes(),
    "Podgorica".as_bytes(),
    "Pointe-Noire".as_bytes(),
    "Pontianak".as_bytes(),
    "Port Moresby".as_bytes(),
    "Port Sudan".as_bytes(),
    "Port Vila".as_bytes(),
    "Port-Gentil".as_bytes(),
    "Portland (OR)".as_bytes(),
    "Porto".as_bytes(),
    "Prague".as_bytes(),
    "Praia".as_bytes(),
    "Pretoria".as_bytes(),
    "Pyongyang".as_bytes(),
    "Rabat".as_bytes(),
    "Rangpur".as_bytes(),
    "Reggane".as_bytes(),
    "Reykjavík".as_bytes(),
    "Riga".as_bytes(),
    "Riyadh".as_bytes(),
    "Rome".as_bytes(),
    "Roseau".as_bytes(),
    "Rostov-on-Don".as_bytes(),
    "Sacramento".as_bytes(),
    "Saint Petersburg".as_bytes(),
    "Saint-Pierre".as_bytes(),
    "Salt Lake City".as_bytes(),
    "San Antonio".as_bytes(),
    "San Diego".as_bytes(),
    "San Francisco".as_bytes(),
    "San Jose".as_bytes(),
    "San José".as_bytes(),
    "San Juan".as_bytes(),
    "San Salvador".as_bytes(),
    "Sana'a".as_bytes(),
    "Santo Domingo".as_bytes(),
    "Sapporo".as_bytes(),
    "Sarajevo".as_bytes(),
    "Saskatoon".as_bytes(),
    "Seattle".as_bytes(),
    "Seoul".as_bytes(),
    "Seville".as_bytes(),
    "Shanghai".as_bytes(),
    "Singapore".as_bytes(),
    "Skopje".as_bytes(),
    "Sochi".as_bytes(),
    "Sofia".as_bytes(),
    "Sokoto".as_bytes(),
    "Split".as_bytes(),
    "St. John's".as_bytes(),
    "St. Louis".as_bytes(),
    "Stockholm".as_bytes(),
    "Surabaya".as_bytes(),
    "Suva".as_bytes(),
    "Suwałki".as_bytes(),
    "Sydney".as_bytes(),
    "Ségou".as_bytes(),
    "Tabora".as_bytes(),
    "Tabriz".as_bytes(),
    "Taipei".as_bytes(),
    "Tallinn".as_bytes(),
    "Tamale".as_bytes(),
    "Tamanrasset".as_bytes(),
    "Tampa".as_bytes(),
    "Tashkent".as_bytes(),
    "Tauranga".as_bytes(),
    "Tbilisi".as_bytes(),
    "Tegucigalpa".as_bytes(),
    "Tehran".as_bytes(),
    "Tel Aviv".as_bytes(),
    "Thessaloniki".as_bytes(),
    "Thiès".as_bytes(),
    "Tijuana".as_bytes(),
    "Timbuktu".as_bytes(),
    "Tirana".as_bytes(),
    "Toamasina".as_bytes(),
    "Tokyo".as_bytes(),
    "Toliara".as_bytes(),
    "Toluca".as_bytes(),
    "Toronto".as_bytes(),
    "Tripoli".as_bytes(),
    "Tromsø".as_bytes(),
    "Tucson".as_bytes(),
    "Tunis".as_bytes(),
    "Ulaanbaatar".as_bytes(),
    "Upington".as_bytes(),
    "Vaduz".as_bytes(),
    "Valencia".as_bytes(),
    "Valletta".as_bytes(),
    "Vancouver".as_bytes(),
    "Veracruz".as_bytes(),
    "Vienna".as_bytes(),
    "Vientiane".as_bytes(),
    "Villahermosa".as_bytes(),
    "Vilnius".as_bytes(),
    "Virginia Beach".as_bytes(),
    "Vladivostok".as_bytes(),
    "Warsaw".as_bytes(),
    "Washington, D.C.".as_bytes(),
    "Wau".as_bytes(),
    "Wellington".as_bytes(),
    "Whitehorse".as_bytes(),
    "Wichita".as_bytes(),
    "Willemstad".as_bytes(),
    "Winnipeg".as_bytes(),
    "Wrocław".as_bytes(),
    "Xi'an".as_bytes(),
    "Yakutsk".as_bytes(),
    "Yangon".as_bytes(),
    "Yaoundé".as_bytes(),
    "Yellowknife".as_bytes(),
    "Yerevan".as_bytes(),
    "Yinchuan".as_bytes(),
    "Zagreb".as_bytes(),
    "Zanzibar City".as_bytes(),
    "Zürich".as_bytes(),
    "Ürümqi".as_bytes(),
    "İzmir".as_bytes(),
];
